apiVersion: v1 
kind: Service
metadata:
  name: expenses-web-svc
  namespace: dev
spec: 
  type: NodePort
  selector:
    app: expenses-web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080